// Comprehensive Food Nutrition Database for NLP Entity Linking
// Calories and macronutrients per standard serving

const FOOD_DATABASE = [
  // =================== POPULAR COMBOS ===================
  { id: 'combo_burger_fries', name: 'Burger & French Fries Combo', calories: 815, servingUnit: 'combo meal', protein: 28, carbs: 88, fat: 39, category: 'combo', synonyms: ['burger and fries', 'burger with fries', 'burger plus fries', 'burger and chips', 'burger fries combo'] },
  { id: 'combo_burger_fries_coke', name: 'Burger, Fries & Coke Combo', calories: 955, servingUnit: 'combo meal', protein: 28, carbs: 127, fat: 39, category: 'combo', synonyms: ['burger fries and coke', 'burger fries coke', 'burger combo with coke', 'burger meal', 'burger with fries and soda'] },
  { id: 'combo_pizza_coke', name: 'Pizza Slice & Coke Combo', calories: 425, servingUnit: 'combo meal', protein: 12, carbs: 75, fat: 10, category: 'combo', synonyms: ['pizza and coke', 'pizza with coke', 'pizza and soda', 'slice of pizza and coke', 'pizza coke combo'] },
  { id: 'combo_dal_chawal', name: 'Dal Chawal (Rice & Lentils)', calories: 365, servingUnit: 'bowl/plate', protein: 13.2, carbs: 69, fat: 3.9, category: 'combo', synonyms: ['dal chawal', 'daal chawal', 'dal and rice', 'rice and dal', 'dal with rice', 'chawal dal', 'yellow dal and rice'] },
  { id: 'combo_rajma_chawal', name: 'Rajma Chawal (Kidney Beans & Rice)', calories: 425, servingUnit: 'bowl/plate', protein: 17.5, carbs: 81, fat: 3.4, category: 'combo', synonyms: ['rajma chawal', 'rajma and rice', 'rajma with rice', 'rice and rajma'] },
  { id: 'combo_chole_chawal', name: 'Chole Chawal (Chickpeas & Rice)', calories: 445, servingUnit: 'bowl/plate', protein: 16.2, carbs: 80, fat: 6.4, category: 'combo', synonyms: ['chole chawal', 'chole and rice', 'chickpeas and rice', 'chana and rice'] },
  { id: 'combo_chole_bhature', name: 'Chole Bhature (2 Bhature with Chole)', calories: 580, servingUnit: 'plate', protein: 15, carbs: 78, fat: 24, category: 'combo', synonyms: ['chole bhature', 'chola bhatura', 'bhature with chole', 'bhatura chole', '2 bhature and chole'] },
  { id: 'combo_pav_bhaji', name: 'Pav Bhaji (2 Pav with Bhaji)', calories: 400, servingUnit: 'plate', protein: 8, carbs: 62, fat: 14, category: 'combo', synonyms: ['pav bhaji', 'paav bhaji', 'pav with bhaji', '2 pav and bhaji'] },
  { id: 'combo_idli_sambar', name: 'Idli Sambar (2 Idlis with Sambar)', calories: 210, servingUnit: 'plate', protein: 7, carbs: 42, fat: 2, category: 'combo', synonyms: ['idli sambar', 'idlis and sambar', 'idli with sambar', 'idli and chutney'] },
  { id: 'combo_dosa_sambar', name: 'Masala Dosa with Sambar & Chutney', calories: 380, servingUnit: 'plate', protein: 8, carbs: 58, fat: 13, category: 'combo', synonyms: ['dosa and sambar', 'dosa with sambar', 'masala dosa with sambar', 'dosa sambar combo'] },
  { id: 'combo_eggs_toast', name: 'Eggs & Toast (2 Eggs + 1 Toast)', calories: 231, servingUnit: 'serving', protein: 15.2, carbs: 15, fat: 11.6, category: 'combo', synonyms: ['eggs and toast', 'egg and toast', '2 eggs and toast', 'two eggs and toast', 'boiled eggs and toast', 'egg and bread'] },
  { id: 'combo_coffee_croissant', name: 'Coffee & Croissant Combo', calories: 361, servingUnit: 'combo', protein: 8.7, carbs: 42, fat: 16.5, category: 'combo', synonyms: ['coffee and croissant', 'croissant and coffee', 'latte and croissant'] },
  { id: 'combo_chai_samosa', name: 'Chai & Samosa Combo', calories: 350, servingUnit: 'combo', protein: 6, carbs: 46, fat: 16.5, category: 'combo', synonyms: ['chai and samosa', 'tea and samosa', 'samosa with chai', 'samosa and tea'] },
  { id: 'combo_chicken_rice', name: 'Grilled Chicken & Rice Bowl', calories: 370, servingUnit: 'bowl', protein: 35.2, carbs: 45, fat: 4.0, category: 'combo', synonyms: ['chicken and rice', 'chicken with rice', 'grilled chicken and rice', 'chicken rice bowl'] },
  { id: 'combo_fish_chips', name: 'Fish & Chips', calories: 570, servingUnit: 'plate', protein: 26, carbs: 58, fat: 26, category: 'combo', synonyms: ['fish and chips', 'fish with chips', 'fish with fries', 'fried fish and chips'] },
  { id: 'combo_roti_sabzi', name: 'Roti & Sabzi (2 Rotis with Veg Curry)', calories: 380, servingUnit: 'plate', protein: 9, carbs: 56, fat: 12, category: 'combo', synonyms: ['roti and sabzi', 'roti with sabzi', '2 roti and sabzi', 'two rotis and sabzi', 'roti sabzi combo', 'chapati and curry'] },
  { id: 'combo_pancakes_coffee', name: 'Pancakes & Coffee Combo', calories: 480, servingUnit: 'combo', protein: 10, carbs: 76, fat: 13.5, category: 'combo', synonyms: ['pancakes and coffee', 'pancakes with coffee', 'pancake and coffee'] },
  { id: 'combo_steak_potatoes', name: 'Steak & Mashed Potatoes', calories: 410, servingUnit: 'plate', protein: 30, carbs: 37, fat: 15.2, category: 'combo', synonyms: ['steak and potatoes', 'steak with potatoes', 'steak and mashed potatoes'] },

  // =================== FRUITS & DRY FRUITS ===================
  { id: 'apple', name: 'Apple', calories: 95, servingUnit: 'medium', protein: 0.5, carbs: 25, fat: 0.3, category: 'fruit', synonyms: ['apple', 'apples', 'red apple', 'green apple', 'seb'] },
  { id: 'banana', name: 'Banana', calories: 105, servingUnit: 'medium', protein: 1.3, carbs: 27, fat: 0.4, category: 'fruit', synonyms: ['banana', 'bananas', 'ripe banana', 'kela'] },
  { id: 'orange', name: 'Orange', calories: 62, servingUnit: 'medium', protein: 1.2, carbs: 15.4, fat: 0.2, category: 'fruit', synonyms: ['orange', 'oranges', 'tangerine', 'santra'] },
  { id: 'mango', name: 'Mango', calories: 150, servingUnit: 'cup', protein: 1.4, carbs: 35, fat: 0.6, category: 'fruit', synonyms: ['mango', 'mangoes', 'aam', 'slice of mango'] },
  { id: 'grapes', name: 'Grapes', calories: 104, servingUnit: 'cup', protein: 1.1, carbs: 27, fat: 0.2, category: 'fruit', synonyms: ['grapes', 'grape', 'green grapes', 'red grapes', 'angoor'] },
  { id: 'strawberries', name: 'Strawberries', calories: 50, servingUnit: 'cup', protein: 1.0, carbs: 11.7, fat: 0.5, category: 'fruit', synonyms: ['strawberry', 'strawberries'] },
  { id: 'blueberries', name: 'Blueberries', calories: 84, servingUnit: 'cup', protein: 1.1, carbs: 21.4, fat: 0.5, category: 'fruit', synonyms: ['blueberry', 'blueberries'] },
  { id: 'avocado', name: 'Avocado', calories: 240, servingUnit: 'medium', protein: 3.0, carbs: 12, fat: 22, category: 'fruit', synonyms: ['avocado', 'avocados', 'hass avocado'] },
  { id: 'watermelon', name: 'Watermelon', calories: 85, servingUnit: 'wedge', protein: 1.7, carbs: 21, fat: 0.4, category: 'fruit', synonyms: ['watermelon', 'water melon', 'tarbooz'] },
  { id: 'papaya', name: 'Papaya', calories: 120, servingUnit: 'bowl', protein: 1.9, carbs: 30, fat: 0.4, category: 'fruit', synonyms: ['papaya', 'papitas'] },
  { id: 'pineapple', name: 'Pineapple', calories: 82, servingUnit: 'cup', protein: 0.9, carbs: 21.6, fat: 0.2, category: 'fruit', synonyms: ['pineapple', 'pineapples', 'ananas'] },
  { id: 'kiwi', name: 'Kiwi Fruit', calories: 42, servingUnit: 'piece', protein: 0.8, carbs: 10, fat: 0.4, category: 'fruit', synonyms: ['kiwi', 'kiwis', 'kiwi fruit'] },
  { id: 'pomegranate', name: 'Pomegranate', calories: 134, servingUnit: 'cup', protein: 2.9, carbs: 32, fat: 1.9, category: 'fruit', synonyms: ['pomegranate', 'anaar', 'anar'] },
  { id: 'dates', name: 'Dates (Khajoor, 3 pcs)', calories: 60, servingUnit: '3 pieces', protein: 0.5, carbs: 16, fat: 0.1, category: 'fruit', synonyms: ['dates', 'date', 'khajoor'] },
  { id: 'almonds', name: 'Almonds (handful)', calories: 160, servingUnit: 'handful (~23 nuts)', protein: 6, carbs: 6, fat: 14, category: 'snack', synonyms: ['almonds', 'almond', 'badam'] },
  { id: 'walnuts', name: 'Walnuts (Akhrot)', calories: 185, servingUnit: 'handful (~7 nuts)', protein: 4.3, carbs: 3.9, fat: 18.5, category: 'snack', synonyms: ['walnuts', 'walnut', 'akhrot'] },
  { id: 'cashews', name: 'Cashews (Kaju)', calories: 157, servingUnit: 'handful (28g)', protein: 5.2, carbs: 8.6, fat: 12.4, category: 'snack', synonyms: ['cashews', 'cashew', 'kaju'] },
  { id: 'peanuts', name: 'Roasted Peanuts', calories: 170, servingUnit: 'handful (30g)', protein: 7.5, carbs: 5, fat: 14.5, category: 'snack', synonyms: ['peanuts', 'peanut', 'groundnuts', 'moongphali'] },

  // =================== BREAKFAST & BAKERY ===================
  { id: 'egg', name: 'Boiled Egg', calories: 78, servingUnit: 'large', protein: 6.3, carbs: 0.6, fat: 5.3, category: 'breakfast', synonyms: ['egg', 'eggs', 'boiled egg', 'boiled eggs', 'hard boiled egg', 'anda'] },
  { id: 'fried_egg', name: 'Fried Egg', calories: 92, servingUnit: 'large', protein: 6.3, carbs: 0.4, fat: 7.0, category: 'breakfast', synonyms: ['fried egg', 'fried eggs', 'sunny side up', 'omelette', 'omelet'] },
  { id: 'egg_whites', name: 'Egg Whites (2 large)', calories: 34, servingUnit: '2 egg whites', protein: 7.2, carbs: 0.4, fat: 0.1, category: 'breakfast', synonyms: ['egg whites', 'egg white'] },
  { id: 'scrambled_eggs', name: 'Scrambled Eggs (2 eggs)', calories: 180, servingUnit: 'serving', protein: 12, carbs: 2, fat: 14, category: 'breakfast', synonyms: ['scrambled eggs', 'scrambled egg', 'egg bhurji'] },
  { id: 'bread_slice', name: 'Bread Slice', calories: 75, servingUnit: 'slice', protein: 2.6, carbs: 13.8, fat: 1.0, category: 'bakery', synonyms: ['bread', 'bread slice', 'toast', 'white bread', 'brown bread', 'whole wheat bread'] },
  { id: 'croissant', name: 'Butter Croissant', calories: 231, servingUnit: 'piece', protein: 4.7, carbs: 26, fat: 12, category: 'bakery', synonyms: ['croissant', 'croissants'] },
  { id: 'bagel', name: 'Plain Bagel', calories: 250, servingUnit: 'piece', protein: 10, carbs: 48, fat: 1.5, category: 'bakery', synonyms: ['bagel', 'bagels'] },
  { id: 'pancakes', name: 'Pancakes (2 with syrup)', calories: 350, servingUnit: 'serving', protein: 6, carbs: 60, fat: 9, category: 'breakfast', synonyms: ['pancake', 'pancakes', 'hotcakes'] },
  { id: 'waffles', name: 'Belgian Waffle with Syrup', calories: 310, servingUnit: 'piece', protein: 5, carbs: 45, fat: 12, category: 'breakfast', synonyms: ['waffle', 'waffles', 'belgian waffle'] },
  { id: 'oatmeal', name: 'Oatmeal (cooked with water/milk)', calories: 150, servingUnit: 'bowl', protein: 5.0, carbs: 27, fat: 2.5, category: 'breakfast', synonyms: ['oats', 'oatmeal', 'porridge', 'bowl of oats'] },
  { id: 'cereal', name: 'Breakfast Cereal with Milk', calories: 210, servingUnit: 'bowl', protein: 7.0, carbs: 38, fat: 3.5, category: 'breakfast', synonyms: ['cereal', 'cornflakes', 'corn flakes', 'muesli', 'granola'] },
  { id: 'poha', name: 'Poha with Peanuts', calories: 220, servingUnit: 'plate', protein: 4.5, carbs: 42, fat: 5, category: 'breakfast', synonyms: ['poha', 'kanda poha', 'plate of poha'] },
  { id: 'upma', name: 'Suji Upma', calories: 200, servingUnit: 'bowl', protein: 4, carbs: 38, fat: 4.5, category: 'breakfast', synonyms: ['upma', 'rava upma'] },

  // =================== GRAINS, CURRIES & INDIAN ===================
  { id: 'white_rice', name: 'White Rice (cooked)', calories: 205, servingUnit: 'cup', protein: 4.2, carbs: 45, fat: 0.4, category: 'grain', synonyms: ['rice', 'white rice', 'cooked rice', 'bowl of rice', 'cup of rice', 'chawal', 'steamed rice'] },
  { id: 'brown_rice', name: 'Brown Rice', calories: 218, servingUnit: 'cup', protein: 4.5, carbs: 45.8, fat: 1.6, category: 'grain', synonyms: ['brown rice', 'cooked brown rice'] },
  { id: 'biryani', name: 'Chicken Biryani', calories: 450, servingUnit: 'plate', protein: 24, carbs: 54, fat: 16, category: 'indian', synonyms: ['chicken biryani', 'biryani', 'dum biryani', 'plate of biryani'] },
  { id: 'veg_biryani', name: 'Vegetable Biryani / Pulao', calories: 340, servingUnit: 'plate', protein: 7, carbs: 58, fat: 9, category: 'indian', synonyms: ['veg biryani', 'vegetable biryani', 'pulao', 'veg pulao', 'peas pulao'] },
  { id: 'roti', name: 'Roti / Chapati', calories: 110, servingUnit: 'piece', protein: 3.1, carbs: 22, fat: 1.2, category: 'grain', synonyms: ['roti', 'rotis', 'chapati', 'chapatis', 'phulka', 'flatbread'] },
  { id: 'paratha', name: 'Plain / Aloo Paratha', calories: 260, servingUnit: 'piece', protein: 5.0, carbs: 38, fat: 10, category: 'grain', synonyms: ['paratha', 'parathas', 'aloo paratha', 'stuffed paratha'] },
  { id: 'naan', name: 'Butter Naan', calories: 310, servingUnit: 'piece', protein: 9, carbs: 45, fat: 10, category: 'grain', synonyms: ['naan', 'butter naan', 'garlic naan'] },
  { id: 'puri', name: 'Poori / Puri (2 pieces)', calories: 240, servingUnit: '2 pieces', protein: 3.5, carbs: 28, fat: 13, category: 'indian', synonyms: ['puri', 'poori', 'puris', 'pooris'] },
  { id: 'dal', name: 'Dal / Lentil Soup', calories: 160, servingUnit: 'bowl', protein: 9, carbs: 24, fat: 3.5, category: 'protein', synonyms: ['dal', 'daal', 'yellow dal', 'lentil soup', 'tadka dal', 'sambhar', 'sambar'] },
  { id: 'dal_makhani', name: 'Dal Makhani', calories: 280, servingUnit: 'bowl', protein: 10, carbs: 28, fat: 15, category: 'indian', synonyms: ['dal makhani', 'daal makhni', 'makhani dal'] },
  { id: 'paneer_butter_masala', name: 'Paneer Butter Masala', calories: 340, servingUnit: 'bowl', protein: 14, carbs: 12, fat: 26, category: 'indian', synonyms: ['paneer butter masala', 'shahi paneer', 'paneer makhani'] },
  { id: 'palak_paneer', name: 'Palak Paneer', calories: 270, servingUnit: 'bowl', protein: 15, carbs: 9, fat: 19, category: 'indian', synonyms: ['palak paneer', 'saag paneer'] },
  { id: 'chicken_curry', name: 'Chicken Curry', calories: 320, servingUnit: 'bowl', protein: 26, carbs: 8, fat: 20, category: 'protein', synonyms: ['chicken curry', 'chicken gravy', 'butter chicken', 'chicken tikka masala'] },
  { id: 'tandoori_chicken', name: 'Tandoori Chicken (1 leg/breast)', calories: 220, servingUnit: 'piece', protein: 30, carbs: 3, fat: 9, category: 'protein', synonyms: ['tandoori chicken', 'chicken tikka'] },
  { id: 'chickpeas', name: 'Chickpeas / Chana Masala', calories: 240, servingUnit: 'bowl', protein: 12, carbs: 35, fat: 6, category: 'protein', synonyms: ['chana', 'chickpeas', 'chana masala', 'chole', 'garbanzo beans'] },
  { id: 'kidney_beans', name: 'Rajma / Kidney Beans', calories: 220, servingUnit: 'bowl', protein: 13, carbs: 36, fat: 3, category: 'protein', synonyms: ['rajma', 'kidney beans'] },
  { id: 'aloo_gobi', name: 'Aloo Gobi', calories: 170, servingUnit: 'bowl', protein: 4, carbs: 24, fat: 7, category: 'indian', synonyms: ['aloo gobi', 'aloo gobhi', 'potato cauliflower'] },

  // =================== PROTEINS & MEATS ===================
  { id: 'chicken_breast', name: 'Grilled Chicken Breast', calories: 165, servingUnit: '100g', protein: 31, carbs: 0, fat: 3.6, category: 'protein', synonyms: ['chicken', 'chicken breast', 'grilled chicken', 'baked chicken', 'chicken fillet', 'murgh'] },
  { id: 'salmon', name: 'Grilled Salmon', calories: 206, servingUnit: 'fillet', protein: 22, carbs: 0, fat: 12.3, category: 'protein', synonyms: ['salmon', 'grilled salmon', 'salmon fillet', 'fish fillet', 'fish'] },
  { id: 'tuna', name: 'Canned Tuna in Water', calories: 130, servingUnit: 'can', protein: 28, carbs: 0, fat: 1.0, category: 'protein', synonyms: ['tuna', 'canned tuna', 'tuna fish'] },
  { id: 'paneer', name: 'Paneer (Cottage Cheese)', calories: 265, servingUnit: '100g', protein: 18, carbs: 3.5, fat: 20, category: 'protein', synonyms: ['paneer', 'cottage cheese', 'paneer cubes', 'paneer tikka'] },
  { id: 'tofu', name: 'Firm Tofu', calories: 144, servingUnit: '100g', protein: 17, carbs: 3.0, fat: 8.0, category: 'protein', synonyms: ['tofu', 'firm tofu', 'fried tofu'] },
  { id: 'beef_steak', name: 'Lean Beef Steak', calories: 250, servingUnit: '100g', protein: 26, carbs: 0, fat: 15, category: 'protein', synonyms: ['steak', 'beef steak', 'beef', 'roast beef'] },
  { id: 'protein_shake', name: 'Whey Protein Shake', calories: 140, servingUnit: 'scoop with water', protein: 25, carbs: 3, fat: 1.5, category: 'fitness', synonyms: ['protein shake', 'whey protein', 'protein drink', 'whey'] },
  { id: 'peanut_butter', name: 'Peanut Butter', calories: 95, servingUnit: 'tbsp', protein: 4, carbs: 3.5, fat: 8, category: 'snack', synonyms: ['peanut butter', 'spoon of peanut butter'] },

  // =================== FAST FOOD, STREET FOOD & SNACKS ===================
  { id: 'pizza', name: 'Pizza (Regular Slice)', calories: 285, servingUnit: 'slice', protein: 12, carbs: 36, fat: 10, category: 'fast_food', synonyms: ['pizza', 'slice of pizza', 'cheese pizza', 'pepperoni pizza', 'pizza slice'] },
  { id: 'burger', name: 'Cheeseburger', calories: 450, servingUnit: 'piece', protein: 24, carbs: 40, fat: 22, category: 'fast_food', synonyms: ['burger', 'cheeseburger', 'hamburger', 'veggie burger', 'chicken burger'] },
  { id: 'french_fries', name: 'French Fries', calories: 365, servingUnit: 'medium serving', protein: 4.0, carbs: 48, fat: 17, category: 'fast_food', synonyms: ['fries', 'french fries', 'potato fries', 'chips'] },
  { id: 'pasta', name: 'Pasta (cooked with sauce)', calories: 280, servingUnit: 'bowl', protein: 9, carbs: 48, fat: 5, category: 'grain', synonyms: ['pasta', 'spaghetti', 'penne', 'macaroni', 'bowl of pasta', 'white sauce pasta', 'red sauce pasta'] },
  { id: 'noodles', name: 'Noodles / Chow Mein', calories: 320, servingUnit: 'bowl', protein: 7, carbs: 54, fat: 9, category: 'fast_food', synonyms: ['noodles', 'chow mein', 'chowmein', 'hakka noodles', 'maggi', 'instant noodles'] },
  { id: 'momos', name: 'Momos / Dim Sum (6 pieces)', calories: 240, servingUnit: 'plate (6 pcs)', protein: 10, carbs: 34, fat: 7, category: 'snack', synonyms: ['momos', 'momo', 'steamed momos', 'fried momos', 'dim sums'] },
  { id: 'samosa', name: 'Fried Samosa', calories: 260, servingUnit: 'piece', protein: 4, carbs: 32, fat: 14, category: 'snack', synonyms: ['samosa', 'samosas'] },
  { id: 'subway_sandwich', name: 'Sandwich (6 inch sub)', calories: 380, servingUnit: 'piece', protein: 18, carbs: 46, fat: 12, category: 'fast_food', synonyms: ['sandwich', 'sub', 'club sandwich', 'chicken sandwich', 'veg sandwich'] },
  { id: 'hot_dog', name: 'Hot Dog', calories: 290, servingUnit: 'piece', protein: 10, carbs: 24, fat: 16, category: 'fast_food', synonyms: ['hot dog', 'hotdog'] },
  { id: 'bhel_puri', name: 'Bhel Puri / Chaat', calories: 210, servingUnit: 'plate', protein: 5, carbs: 42, fat: 3.5, category: 'snack', synonyms: ['bhel', 'bhel puri', 'chaat', 'sev puri', 'pani puri', 'golgappa'] },
  { id: 'vada_pav', name: 'Vada Pav', calories: 290, servingUnit: 'piece', protein: 6, carbs: 44, fat: 10, category: 'snack', synonyms: ['vada pav', 'wada pav', 'batata vada'] },
  { id: 'chicken_nuggets', name: 'Chicken Nuggets (6 pieces)', calories: 280, servingUnit: '6 pieces', protein: 14, carbs: 18, fat: 17, category: 'fast_food', synonyms: ['nuggets', 'chicken nuggets', '6 nuggets'] },
  { id: 'cookie', name: 'Chocolate Chip Cookie', calories: 140, servingUnit: 'cookie', protein: 1.5, carbs: 19, fat: 7, category: 'snack', synonyms: ['cookie', 'cookies', 'biscuit', 'biscuits'] },
  { id: 'potato_chips', name: 'Potato Chips (Bag)', calories: 150, servingUnit: 'pack (28g)', protein: 2, carbs: 15, fat: 10, category: 'snack', synonyms: ['potato chips', 'lays', 'crisps'] },
  { id: 'chocolate', name: 'Chocolate Bar', calories: 220, servingUnit: 'bar (45g)', protein: 3, carbs: 26, fat: 13, category: 'snack', synonyms: ['chocolate', 'dark chocolate', 'milk chocolate', 'dairy milk'] },
  { id: 'ice_cream', name: 'Ice Cream (1 scoop)', calories: 200, servingUnit: 'scoop', protein: 3.5, carbs: 24, fat: 11, category: 'snack', synonyms: ['ice cream', 'icecream', 'scoop of ice cream'] },
  { id: 'brownie', name: 'Chocolate Brownie', calories: 290, servingUnit: 'piece', protein: 4, carbs: 38, fat: 14, category: 'dessert', synonyms: ['brownie', 'chocolate brownie', 'walnut brownie'] },
  { id: 'gulab_jamun', name: 'Gulab Jamun (2 pieces)', calories: 300, servingUnit: '2 pieces', protein: 4, carbs: 48, fat: 11, category: 'dessert', synonyms: ['gulab jamun', 'gulabjamun', 'two gulab jamun'] },

  // =================== DAIRY & VEGETABLES ===================
  { id: 'milk', name: 'Milk (whole)', calories: 150, servingUnit: 'glass (250ml)', protein: 8, carbs: 12, fat: 8, category: 'dairy', synonyms: ['milk', 'glass of milk', 'whole milk', 'cup of milk', 'doodh'] },
  { id: 'skim_milk', name: 'Skim / Low Fat Milk', calories: 90, servingUnit: 'glass (250ml)', protein: 8.5, carbs: 12, fat: 0.5, category: 'dairy', synonyms: ['skim milk', 'low fat milk', 'toned milk'] },
  { id: 'greek_yogurt', name: 'Greek Yogurt', calories: 130, servingUnit: 'cup', protein: 15, carbs: 6, fat: 4, category: 'dairy', synonyms: ['greek yogurt', 'plain greek yogurt', 'curd', 'dahi', 'yogurt'] },
  { id: 'cheddar_cheese', name: 'Cheddar Cheese', calories: 115, servingUnit: 'slice', protein: 7, carbs: 0.4, fat: 9.5, category: 'dairy', synonyms: ['cheese', 'cheese slice', 'cheddar', 'cheddar cheese'] },
  { id: 'salad', name: 'Mixed Green Salad', calories: 85, servingUnit: 'bowl', protein: 2.5, carbs: 10, fat: 4.5, category: 'vegetable', synonyms: ['salad', 'green salad', 'mixed salad', 'garden salad'] },
  { id: 'broccoli', name: 'Steamed Broccoli', calories: 55, servingUnit: 'cup', protein: 3.7, carbs: 11, fat: 0.6, category: 'vegetable', synonyms: ['broccoli', 'steamed broccoli'] },
  { id: 'spinach', name: 'Cooked Spinach / Palak', calories: 41, servingUnit: 'cup', protein: 5.3, carbs: 6.7, fat: 0.5, category: 'vegetable', synonyms: ['spinach', 'palak', 'cooked spinach'] },
  { id: 'potato', name: 'Boiled / Baked Potato', calories: 160, servingUnit: 'medium', protein: 4.3, carbs: 37, fat: 0.2, category: 'vegetable', synonyms: ['potato', 'baked potato', 'boiled potato', 'aloo'] },
  { id: 'cucumber', name: 'Cucumber', calories: 16, servingUnit: 'medium', protein: 0.7, carbs: 3.6, fat: 0.1, category: 'vegetable', synonyms: ['cucumber', 'kheera', 'cucumber slices'] },
  { id: 'tomato', name: 'Tomato', calories: 22, servingUnit: 'medium', protein: 1.1, carbs: 4.8, fat: 0.2, category: 'vegetable', synonyms: ['tomato', 'tomatoes', 'tamatar'] },

  // =================== BEVERAGES & SHAKES ===================
  { id: 'coffee_black', name: 'Black Coffee (no sugar)', calories: 5, servingUnit: 'cup', protein: 0.3, carbs: 0, fat: 0, category: 'beverage', synonyms: ['black coffee', 'coffee', 'espresso', 'americano'] },
  { id: 'coffee_latte', name: 'Coffee with Milk & Sugar / Latte', calories: 130, servingUnit: 'cup', protein: 4, carbs: 16, fat: 4.5, category: 'beverage', synonyms: ['latte', 'cappuccino', 'coffee with milk', 'sweet coffee', 'nescafe'] },
  { id: 'cold_coffee', name: 'Cold Coffee with Ice Cream', calories: 280, servingUnit: 'glass', protein: 6, carbs: 36, fat: 12, category: 'beverage', synonyms: ['cold coffee', 'iced coffee', 'frappe'] },
  { id: 'tea', name: 'Tea with Milk & Sugar (Chai)', calories: 90, servingUnit: 'cup', protein: 2, carbs: 14, fat: 2.5, category: 'beverage', synonyms: ['tea', 'chai', 'milk tea', 'cup of tea', 'hot tea'] },
  { id: 'green_tea', name: 'Green Tea (unsweetened)', calories: 2, servingUnit: 'cup', protein: 0, carbs: 0, fat: 0, category: 'beverage', synonyms: ['green tea', 'herbal tea', 'lemon tea'] },
  { id: 'soda', name: 'Soda / Cola (can 330ml)', calories: 140, servingUnit: 'can', protein: 0, carbs: 39, fat: 0, category: 'beverage', synonyms: ['coke', 'coca cola', 'pepsi', 'soda', 'soft drink', 'can of coke'] },
  { id: 'diet_coke', name: 'Diet Soda / Zero Coke', calories: 1, servingUnit: 'can', protein: 0, carbs: 0, fat: 0, category: 'beverage', synonyms: ['diet coke', 'coke zero', 'diet pepsi', 'sugar free soda'] },
  { id: 'orange_juice', name: 'Fresh Orange Juice', calories: 110, servingUnit: 'glass (250ml)', protein: 1.7, carbs: 26, fat: 0.5, category: 'beverage', synonyms: ['orange juice', 'fruit juice', 'juice', 'glass of juice'] },
  { id: 'mango_shake', name: 'Mango Shake', calories: 250, servingUnit: 'glass', protein: 5, carbs: 46, fat: 6, category: 'beverage', synonyms: ['mango shake', 'mango smoothie'] },
  { id: 'banana_shake', name: 'Banana Shake', calories: 230, servingUnit: 'glass', protein: 5.5, carbs: 42, fat: 5, category: 'beverage', synonyms: ['banana shake', 'banana smoothie'] },
  { id: 'lassi', name: 'Sweet Lassi', calories: 220, servingUnit: 'glass', protein: 6, carbs: 35, fat: 7, category: 'beverage', synonyms: ['lassi', 'sweet lassi', 'punjabi lassi'] },
  { id: 'chaas', name: 'Chaas / Buttermilk', calories: 45, servingUnit: 'glass', protein: 2.5, carbs: 4, fat: 1.5, category: 'beverage', synonyms: ['chaas', 'buttermilk', 'mattha'] },
  { id: 'beer', name: 'Beer (1 pint / 500ml)', calories: 215, servingUnit: 'pint', protein: 2, carbs: 18, fat: 0, category: 'beverage', synonyms: ['beer', 'pint of beer', 'can of beer'] }
];

module.exports = { FOOD_DATABASE };
